<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_product</name>
   <tag></tag>
   <elementGuidId>cdd4842a-9587-4207-b9ca-139a8b4534a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(),'Products')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(),'Products')]</value>
      <webElementGuid>b09726d6-b097-46c7-9ee5-09a07a0672a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
