<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_menu</name>
   <tag></tag>
   <elementGuidId>02ebf3d4-71c3-465d-947c-e8292ab1df75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(@id,'react-burger-menu-btn')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(@id,'react-burger-menu-btn')]</value>
      <webElementGuid>bd86df53-58c0-48f8-b605-9424fb7c6118</webElementGuid>
   </webElementProperties>
</WebElementEntity>
