<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_logout</name>
   <tag></tag>
   <elementGuidId>c649d937-e7a6-4943-9a9e-83ec722da417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@id,'logout_sidebar_link')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@id,'logout_sidebar_link')]</value>
      <webElementGuid>50f8a172-19e2-479e-bc9c-c82b1d0de5bf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
